version: "3.1"
services:
  app:
      build:
          context: ./
      volumes:
        - .:/go/src/app:rw
      ports:
        - "6000:6000"
      container_name: goapp-challenge
  db:
      image: mysql:latest
      ports:
        - 3305:3306
      security_opt:
        - seccomp:unconfined
      environment:
          MYSQL_ROOT_PASSWORD: "${DB_PASSWORD}"
          MYSQL_PASSWORD: "${DB_PASSWORD}"
          MYSQL_DATABASE: "${DB_NAME}"
          MYSQL_USER: "{MYSQL_USER}"
      container_name: goapp-challenge-database
      command:
        - --default-authentication-plugin=mysql_native_password
      healthcheck:
        test: ["CMD-SHELL","echo 'select 1' | mysql -uroot ppanini --silent"]
        interval: 10s
        timeout: 20s
        retries: 6
